version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-net

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/your_database_name
    depends_on:
      - mongodb
    networks:
      - app-net

  admin:
    build: ./admin
    container_name: admin_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  mongo_data:
    driver: local

networks:
  app-net:
    driver: bridge
