apiVersion: v1
kind: Namespace
metadata:
  name: food-delivery
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: food-delivery
data:
  PORT: "4000"
  MONGO_URL: "mongodb://mongo-0.mongo:27017/food-delivery"
