apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: food-delivery
type: Opaque
stringData:
  JWT_SECRET: "4185f9e359e283f603c7ef94e6c37865b5e418ad6c01ecca1fd94fa591bff6b2"
  STRIPE_SECRET_KEY: "sk_test_placeholder"
  SALT: "10"
