apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  PORT: {{ .Values.config.PORT | quote }}
  MONGO_URL: {{ .Values.config.MONGO_URL | quote }}
