apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secret.STRIPE_SECRET_KEY | quote }}
  SALT: {{ .Values.secret.SALT | quote }}
