helm:
  parameters:
  - name: backend.repository
    value: tahoordocker/fda-backend
    forcestring: true
  - name: backend.tag
    value: "1"
    forcestring: true
  - name: frontend.repository
    value: tahoordocker/fda-frontend
    forcestring: true
  - name: frontend.tag
    value: "1"
    forcestring: true
